# Generated by Django 4.2.7 on 2023-11-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('national_id', models.TextField()),
                ('national_id_type', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
    ]
